version: '3.8'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=usuarios
      - MYSQL_USER=dbauser
      - MYSQL_PASSWORD=password 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 
    volumes:
      - "./db:/docker-entrypoint-initdb.d" 
  www:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - "./:/var/www/html" 
    ports:
      - 80:80
      - 443:443 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - "8080:8080"
     - "50000:50000"
    container_name: jenkins
    volumes:
     - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    #image: prom/prometheus:v2.32.1
    image: prom/prometheus-linux-arm64:v2.40.2
    user: root
    volumes:
      - "./etc/prometheus/:/etc/prometheus/"
      - "./var/prometheus/prometheus_data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    user: root
    ports:
      - "3000:3000"
    volumes:
      - "./var/grafana/grafana_data:/var/lib/grafana"
      - "./etc/grafana/provisioning/:/etc/grafana/provisioning/"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_USERS_ALLOW_SIGN_UP=false
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - 8090:8080
  alertmanager:
    image: prom/alertmanager:v0.24.0
    ports:
      - 9093:9093
    volumes:
      - ./etc/alertmanager/:/etc/alertmanager/
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
  mysqld_exporter:
    image: prom/mysqld-exporter
    user: root
    ports:
      - "9104:9104"
    environment:
      - "DATA_SOURCE_NAME=root:password@(db:3306)/db"
      - "collect.info_schema.tablestats=true"
      - "collect.info_schema.userstats=true"
      - "collect.info_schema.query_response_time=true"
      - "collect.auto_increment.columns=true"
      - "collect.perf_schema.tableiowaits=true"
      - "collect.perf_schema.tablelocks=true"
    depends_on:
      - db
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    depends_on:
      - prometheus