version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=usuarios
      - MYSQL_USER=dbauser
      - MYSQL_PASSWORD=password 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 
    volumes:
      - "./db:/docker-entrypoint-initdb.d" 
  www:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - "./:/var/www/html" 
    ports:
      - 80:80
      - 443:443 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  jenkins:
    container_name: jenkins
    privileged: true
    user: root
    image: jenkins:2.60.3
    ports:
     - "8085:8080"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/local/bin/docker:/usr/local/bin/docker